version: 0.2

phases:
  build:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Executing pre-build commands"
  build:
    commands:
      - echo "Zipping deployment package..."
      - mvn clean package 
  post_build:
    commands:
     - echo "Updating lambda Function..."
     - aws lambda update-function-code --function-name java17lambdatest --zip-file fileb://target/lambda_java_sample.jar
artifacts:
  files:
    - target/lambda_java_sample.jar
  discard-paths: yes